import { _electron as electron } from 'playwright';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import AxeBuilder from '@axe-core/playwright';
const directory = await mkdtemp(path.join(os.tmpdir(), 'svara-ui-'));
const env = { ...process.env, SVARA_TEST_USER_DATA: directory, SVARA_TEST_HEADLESS: '1' };
delete env.ELECTRON_RUN_AS_NODE;
const packaged = process.env.SVARA_PACKAGED_EXECUTABLE;
const app = await electron.launch({ ...(packaged ? { executablePath: packaged } : {}), args: packaged ? [] : ['.'], env, timeout: 30000 });
const errors = [];
try {
  const window = await app.firstWindow();
  window.on('pageerror', error => errors.push(error.message));
  await window.waitForSelector('#talk');
  await window.waitForFunction(() => document.querySelector('#status-message').textContent.includes('Your browser'));
  const audit = async label => {
    const result = await new AxeBuilder({ page: window }).setLegacyMode(true).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
    assert.deepEqual(result.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })), [], `${label} accessibility`);
  };
  await audit('Home');
  await mkdir('artifacts', { recursive: true });
  await window.screenshot({ path: 'artifacts/home.png' });
  assert.equal(await window.evaluate(() => typeof window.require), 'undefined');
  await window.getByRole('button', { name: 'Try practice mode' }).click();
  await window.waitForFunction(() => document.querySelectorAll('.item-button').length === 5);
  await window.getByRole('button', { name: 'Read next item', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#position').textContent === '2 / 5');
  await window.getByRole('button', { name: 'Read previous item', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#position').textContent === '1 / 5');
  await window.getByRole('button', { name: 'Headings', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('[data-scope="headings"]').getAttribute('aria-pressed') === 'true');
  await window.getByRole('button', { name: 'Results', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#position').textContent === '1 / 5');
  await window.screenshot({ path: 'artifacts/reader.png', fullPage: true });
  await audit('Reader');
  await window.getByRole('button', { name: 'Connections', exact: true }).click();
  await window.locator('#project-id').fill('svara-test-project');
  await window.getByRole('button', { name: 'Save connections', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#notice').textContent.includes('saved'));
  await window.screenshot({ path: 'artifacts/connections.png', fullPage: true });
  await audit('Connections');
  await window.getByRole('button', { name: 'Home', exact: true }).click();
  await window.locator('#command-input').fill('next');
  await window.getByRole('button', { name: 'Send command', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#position').textContent === '2 / 5');
  await window.keyboard.press('Escape');
  await window.waitForFunction(() => /Stopped|නැවැත්තුවා/.test(document.querySelector('#status-message').textContent));
  assert.deepEqual(errors, []);
  console.log('Desktop UI passed: home, practice, reader navigation, scopes, settings, typed commands, Escape, renderer isolation. Screenshots in artifacts/.');
} finally { await app.close(); await rm(directory, { recursive: true, force: true }); }
