import { _electron as electron } from 'playwright';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import AxeBuilder from '@axe-core/playwright';
import { testInteractions } from './test-interactions.js';
const directory = await mkdtemp(path.join(os.tmpdir(), 'svara-ui-'));
const env = { ...process.env, SVARA_TEST_USER_DATA: directory, SVARA_TEST_HEADLESS: '1' };
delete env.ELECTRON_RUN_AS_NODE;
const packaged = process.env.SVARA_PACKAGED_EXECUTABLE;
const app = await electron.launch({ ...(packaged ? { executablePath: packaged } : {}), args: packaged ? [] : ['.'], env, timeout: 30000 });
const errors = [];
try {
  const window = await app.firstWindow();
  window.setDefaultTimeout(10000);
  window.on('pageerror', error => errors.push(error.message));
  await window.waitForSelector('#talk');
  await window.waitForFunction(() => document.querySelector('#status-message').textContent.includes('Your browser'));
  // Exercise native-speech wiring, but intercept audio output in this test profile.
  await app.evaluate(() => {
    const childProcess = process.getBuiltinModule('node:child_process');
    const { EventEmitter } = process.getBuiltinModule('node:events');
    const original = childProcess.spawn;
    globalThis.svaraPositionTest = { numbers: [], stops: 0, readings: [], manual: false, waiting: [] };
    childProcess.spawn = (command, args, options) => {
      if (command !== '/usr/bin/say') return original(command, args, options);
      const child = new EventEmitter(); let ended = false;
      child.kill = () => { ended = true; globalThis.svaraPositionTest.stops++; child.emit('exit', null, 'SIGTERM'); };
      if (Array.isArray(options.stdio)) {
        child.stdin = new EventEmitter(); child.stdin.end = text => {
          globalThis.svaraPositionTest.readings.push(text);
          globalThis.svaraInteractionTest?.spoken.push(text);
          const done = () => { if (!ended) child.emit('exit', 0, null); };
          if (globalThis.svaraPositionTest.manual) globalThis.svaraPositionTest.waiting.push(done); else setTimeout(done, 10);
        };
      } else globalThis.svaraPositionTest.numbers.push(Number(args.at(-1)));
      return child;
    };
    process.getBuiltinModule('node:module').syncBuiltinESMExports();
  });
  const expectNumbers = async expected => {
    const numbers = await app.evaluate(async (_electron, count) => {
      const deadline = Date.now() + 2000;
      while (globalThis.svaraPositionTest.numbers.length < count && Date.now() < deadline) await new Promise(resolve => setTimeout(resolve, 10));
      return globalThis.svaraPositionTest.numbers;
    }, expected.length);
    assert.deepEqual(numbers, expected);
  };
  const audit = async label => {
    const result = await new AxeBuilder({ page: window }).setLegacyMode(true).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
    assert.deepEqual(result.violations.map(v => ({ id: v.id, targets: v.nodes.map(n => n.target) })), [], `${label} accessibility`);
  };
  await audit('Home');
  await mkdir('artifacts', { recursive: true });
  await window.screenshot({ path: 'artifacts/home.png' });
  assert.equal(await window.evaluate(() => typeof window.require), 'undefined');
  await window.getByRole('button', { name: 'Try practice mode' }).click();
  await window.waitForFunction(() => document.querySelectorAll('.item-button').length === 5);
  await window.waitForFunction(() => document.activeElement?.dataset.itemIndex === '0');
  await expectNumbers([1]);
  await window.keyboard.press('ArrowDown');
  await window.waitForFunction(() => document.activeElement?.dataset.itemIndex === '1');
  await expectNumbers([1, 2]);
  await window.keyboard.press('ArrowUp');
  await window.waitForFunction(() => document.activeElement?.dataset.itemIndex === '0');
  await expectNumbers([1, 2, 1]);
  const stopsBefore = await app.evaluate(() => globalThis.svaraPositionTest.stops);
  await window.getByRole('button', { name: 'Stop voice', exact: true }).click();
  await window.waitForFunction(() => /Stopped|නැවැත්තුවා/.test(document.querySelector('#status-message').textContent));
  assert.ok(await app.evaluate(() => globalThis.svaraPositionTest.stops) > stopsBefore);
  await window.locator('#read-on-focus').uncheck();
  await window.waitForFunction(async () => (await window.svara.initial()).settings.readOnFocus === false);
  await window.locator('.item-button').nth(0).focus();
  await window.keyboard.press('ArrowDown');
  await window.waitForFunction(() => document.activeElement?.dataset.itemIndex === '1');
  await window.keyboard.press('r');
  await window.waitForFunction(() => document.querySelector('#status-message').textContent.startsWith('2.'));
  await window.keyboard.press('Enter');
  await window.getByRole('button', { name: 'Confirm · තහවුරු කරන්න', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#page-url').textContent.includes('Local practice') && document.querySelector('#position').textContent === '1 / 5');
  assert.match((await window.evaluate(() => window.svara.initial())).state.page.url, /#music$/);
  await window.locator('.item-button').nth(2).click();
  await window.getByRole('button', { name: 'Confirm · තහවුරු කරන්න', exact: true }).click();
  await window.waitForFunction(async () => (await window.svara.initial()).state.page.url.endsWith('#sinhala'));
  await window.evaluate(() => window.svara.startBrowser(true));
  await window.locator('#read-on-focus').check();
  await window.waitForFunction(async () => (await window.svara.initial()).settings.readOnFocus === true);
  await window.getByRole('button', { name: 'Next title', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#position').textContent === '2 / 5');
  await window.getByRole('button', { name: 'Previous title', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#position').textContent === '1 / 5');
  await window.getByRole('button', { name: 'Headings', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('[data-scope="headings"]').getAttribute('aria-pressed') === 'true');
  await window.getByRole('button', { name: 'Results', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#position').textContent === '1 / 5');
  await window.screenshot({ path: 'artifacts/reader.png', fullPage: true });
  await audit('Reader');
  await window.getByRole('button', { name: 'Connections', exact: true }).click();
  await window.locator('#project-id').fill('svara-test-project');
  await window.getByRole('button', { name: 'Save connections', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#notice').textContent.includes('saved'));
  await window.screenshot({ path: 'artifacts/connections.png', fullPage: true });
  await audit('Connections');
  await window.getByRole('button', { name: 'Keyboard shortcuts', exact: true }).click();
  await window.waitForSelector('#view-shortcuts:not([hidden])');
  assert.equal(await app.evaluate(({ globalShortcut }) => globalShortcut.isSuspended()), true);
  await window.getByRole('button', { name: 'Use single keys · F2–F12', exact: true }).click();
  await window.locator('#shortcut-next-key').selectOption('F8');
  await window.getByRole('button', { name: 'Save and use shortcuts', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#shortcut-status').textContent.includes('assigned twice'));
  await window.locator('#shortcut-next-key').selectOption('F7');
  await audit('Keyboard shortcuts');
  await window.locator('#main').focus();
  await window.evaluate(() => window.scrollTo(0, 0));
  await window.screenshot({ path: 'artifacts/shortcuts.png' });
  await window.getByRole('button', { name: 'Save and use shortcuts', exact: true }).click();
  await window.waitForSelector('#view-home:not([hidden])');
  assert.equal(await app.evaluate(({ globalShortcut }) => globalShortcut.isSuspended()), false);
  assert.equal(await app.evaluate(({ globalShortcut }) => ['F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8', 'F9', 'F10', 'F11', 'F12'].every(key => globalShortcut.isRegistered(key))), true);
  assert.equal(await window.locator('.hero [data-shortcut-hint="speak"]').textContent(), 'F8');
  for (const [action, scope] of [['headings', 'headings'], ['page_text', 'article'], ['links', 'links'], ['results', 'results']]) {
    await app.evaluate(({ BrowserWindow }, value) => BrowserWindow.getAllWindows()[0].webContents.send('shortcut-action', value), action);
    await window.waitForFunction(value => document.querySelector(`[data-scope="${value}"]`).getAttribute('aria-pressed') === 'true' && document.activeElement?.dataset.itemIndex === '0', scope);
  }
  // Exercise the same IPC event emitted by the native shortcut callbacks, without recording the user's microphone.
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.send('shortcut-action', 'next'));
  await window.waitForFunction(() => document.querySelector('#position').textContent === '2 / 5');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.send('shortcut-action', 'previous'));
  await window.waitForFunction(() => document.querySelector('#position').textContent === '1 / 5');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].webContents.send('shortcut-action', 'speak-start'));
  await window.waitForFunction(() => document.querySelector('#notice').textContent.includes('Practice mode uses typed commands'));
  await window.reload();
  await window.waitForFunction(() => document.querySelector('.hero [data-shortcut-hint="speak"]').textContent === 'F8');
  await window.getByRole('button', { name: 'Keyboard shortcuts', exact: true }).click();
  await window.waitForSelector('#view-shortcuts:not([hidden])');
  assert.equal(await window.locator('#shortcut-next-key').inputValue(), 'F7');
  assert.equal(await window.locator('#shortcut-headings-key').inputValue(), 'F3');
  assert.equal(await window.locator('#shortcut-first_five-key').inputValue(), 'F11');
  await window.locator('#shortcuts-enabled').uncheck();
  await window.getByRole('button', { name: 'Save and use shortcuts', exact: true }).click();
  await window.waitForSelector('#view-home:not([hidden])');
  assert.equal(await app.evaluate(({ globalShortcut }) => globalShortcut.isRegistered('F8')), false);
  await window.getByRole('button', { name: 'Home', exact: true }).click();
  await window.locator('#command-input').fill('next');
  await window.getByRole('button', { name: 'Send command', exact: true }).click();
  await window.waitForFunction(() => document.querySelector('#position').textContent === '2 / 5');
  await window.keyboard.press('Escape');
  await window.waitForFunction(() => /Stopped|නැවැත්තුවා/.test(document.querySelector('#status-message').textContent));
  await window.getByRole('button', { name: 'Home', exact: true }).click();
  await testInteractions(app, window);
  assert.deepEqual(errors, []);
  console.log('Desktop UI passed: home, practice, reader, settings, shortcut editing, conflicts, native registration, actions, reload persistence, disabling, Escape, and accessibility. Screenshots in artifacts/.');
} catch (error) {
  const window = await app.firstWindow();
  console.error(await window.evaluate(() => ({ notice: document.querySelector('#notice').textContent, status: document.querySelector('#status-message').textContent, position: document.querySelector('#position').textContent, recording: document.querySelector('#talk-label').textContent })));
  console.error(await window.evaluate(() => window.svaraFakeMedia));
  await window.screenshot({ path: 'artifacts/test-failure.png', fullPage: true });
  throw error;
} finally { await app.close(); await rm(directory, { recursive: true, force: true }); }
